---
title: "Plots"
author: "Zoë Hillier-Weltman"
date: "23/08/2022"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(ggplot2)
library(here)
library(tidyverse)
```

birds/scales for top ten species of the three scales
```{r,echo=F}
birds_species_all<-full_join(topten_1,topten_2)
birds_species_all<-full_join(birds_species_all,topten_3)

ggplot(birds_species_all, aes(fill=scale, y=individualCount, x=species))+
geom_bar(position='dodge', stat='identity')+
  theme_classic()+
    xlab("Species")+
  ylab("Number of bird observations")+ 
  scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 10))+
    theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1))
```

birds/regions
```{r}
ggplot(gbif_region_year, aes(x=year, y=n))+
  geom_point()+
  geom_smooth(se=F)+
  coord_cartesian(expand=F)+
  theme_classic()+
  scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 10))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))+
  xlab("Year")+
  ylab("Number of birds observed")+
  ggtitle("Total Regional Bird Counts per Year")
```

birds by month, buffered sites
```{r}
ggplot(birds_seasons_regions,aes(x=month,y=individualCount))+
  geom_point()+
  theme_classic()+
  geom_smooth(se=F)+
  xlab("Month")+
  ylab("Number of birds observed")+
   scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 10))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 12))
```

shrubs and sites
```{r}
birds_seasons_sites_2<-expanded_sites%>%
  group_by(month, individualCount)%>%
  aggregate(individualCount ~month, sum)

ggplot(birds_seasons_sites_2,aes(x=month,y=individualCount))+
  geom_point()+
  theme_classic()+
  geom_smooth(se=F)+
  xlab("Month")+
  ylab("Number of birds observed")+
   scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 10))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 12))
```

shrubs/km^2 and n birds

```{r}
ggplot(birds_shrubs_km_buf, aes(y=individualCount, x=shrubs_km))+
geom_point()+
  theme_classic()+
  geom_smooth(se=F)+
    xlab("Shrubs per square kilometer")+
  ylab("Bird count")+ 
  ggtitle("Shrub Density and Bird Observations at Buffered Sites")+
  scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) 

```

shrub density and sites
```{r}
ggplot(shrubs_by_area_km,aes(x=site_code,y=shrubs_km))+
  theme_classic()+
  geom_col()+
  coord_cartesian(expand=T)+
  xlab("Site")+
  ylab("Shrubs per km^2")+ 
  scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 20))+
  theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1))
```
number of species/site
```{r}
ggplot(n_species_sites,aes(x=site_code,y=species_count))+
  geom_bar(position='dodge', stat='identity')+
  theme_classic()+
  geom_smooth(se=F)+
  xlab("Site")+
  ylab("Number of species")+
   scale_y_continuous(labels=comma,breaks = scales::pretty_breaks(n = 10))+
    theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1))
```

tables of species-regions
```{r}
knitr::kable(topten_5, format="html")
```

table of species-sites
```{r}
knitr::kable(topten_4, format="html")
```

